/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/areas.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/areas.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[49.252, 3.273, 38.521]}>
        <group position={[8.22, -2.65, -6.213]} rotation={[-0.197, -0.44, -0.085]}>
          <mesh geometry={nodes.body002.geometry} material={materials.palette} position={[0, -0.614, 0]} />
          <mesh geometry={nodes.qosdjqosjd.geometry} material={materials.emissiveOrangeRadialGradient} position={[1.255, 0.208, -0.367]} rotation={[-0.148, 0.022, -0.3]} />
        </group>
        <group position={[8.08, -2.759, -8.232]} rotation={[0.244, 0.799, -0.177]}>
          <mesh geometry={nodes.phonePhysicalDynamic.geometry} material={materials.palette} />
          <mesh geometry={nodes.phonePhysicalDynamic002.geometry} material={materials.emissiveOrangeRadialGradient} />
        </group>
        <mesh geometry={nodes.base015.geometry} material={materials.palette} position={[6.905, -2.961, 8.841]} rotation={[-0.268, 0.808, -0.215]} scale={85.968} />
        <mesh geometry={nodes.gizmoPhysicalDynamic.geometry} material={materials.palette} position={[6.021, -2.349, -7.643]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.physicalFixed003.geometry} material={materials.stylizedMap} position={[-4.682, -1.764, -6.749]} rotation={[0.521, -0.31, 0.173]} scale={1.088} />
        <mesh geometry={nodes.physicalFixed009.geometry} material={materials.palette} position={[-3.104, 0, -7.736]} rotation={[0.52, -0.303, 0.169]} />
        <mesh geometry={nodes.Plane002.geometry} material={materials.palette} position={[5.228, -3.124, -8.818]} rotation={[0.183, 0.31, -0.057]} scale={0.581} />
        <mesh geometry={nodes.Plane004.geometry} material={materials.emissiveOrangeRadialGradient} position={[5.228, -3.124, -8.818]} rotation={[0.183, 0.31, -0.057]} scale={0.581} />
        <mesh geometry={nodes.refBonfireBurn001.geometry} material={materials.emissiveOrangeRadialGradient} position={[6.346, -3.298, 8.82]} />
        <mesh geometry={nodes.refBonfireHashes.geometry} material={materials.palette} position={[6.346, -3.286, 8.82]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic010.geometry} material={materials.palette} position={[0.448, -2.528, 0.447]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic011.geometry} material={materials.palette} position={[-0.889, -2.528, 1.071]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic012.geometry} material={materials.palette} position={[-2.34, -2.528, 1.748]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic013.geometry} material={materials.palette} position={[-3.36, -2.528, 2.223]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic014.geometry} material={materials.palette} position={[-4.218, -2.528, 2.623]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic015.geometry} material={materials.palette} position={[-5.802, -2.528, 3.362]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic016.geometry} material={materials.palette} position={[-7.14, -2.528, 3.986]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic017.geometry} material={materials.palette} position={[-8.42, -2.544, 4.583]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic018.geometry} material={materials.palette} position={[-9.638, -2.528, 5.151]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refLettersPhysicalDynamic019.geometry} material={materials.palette} position={[-10.87, -2.528, 5.725]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.sword.geometry} material={materials.redGradient} position={[7.014, -2.078, 8.453]} rotation={[-0.139, -0.083, -0.303]} />
      </group>
      <group position={[25.844, 3.273, -0.905]}>
        <group position={[1.22, -3.232, 7.437]}>
          <mesh geometry={nodes.Plane102.geometry} material={materials.emissiveBlueRadialGradient} />
          <mesh geometry={nodes.Plane102_1.geometry} material={materials.palette} />
          <mesh geometry={nodes.careerText.geometry} material={materials.careerTextHetic} position={[0.866, 0.679, -0.921]} rotation={[1.384, 0.184, -0.768]} scale={[1.565, 1, 0.295]} />
        </group>
        <group position={[1.22, -3.232, 2.438]}>
          <mesh geometry={nodes.Plane095.geometry} material={materials.emissiveOrangeRadialGradient} />
          <mesh geometry={nodes.Plane095_1.geometry} material={materials.palette} />
          <mesh geometry={nodes.careerText001.geometry} material={materials.careerTextUzik} position={[0.331, 0.676, -0.469]} rotation={[1.384, 0.184, -0.768]} scale={[0.83, 1, 0.295]} />
        </group>
        <group position={[1.22, -3.232, -0.582]}>
          <mesh geometry={nodes.Plane081.geometry} material={materials.emissiveOrangeRadialGradient} />
          <mesh geometry={nodes.Plane081_1.geometry} material={materials.palette} />
          <mesh geometry={nodes.careerText002.geometry} material={materials.careerTextImmersive} position={[0.996, 0.642, -0.925]} rotation={[1.384, 0.184, -0.768]} scale={[1.69, 1, 0.295]} />
        </group>
        <group position={[1.22, -3.232, -3.557]}>
          <mesh geometry={nodes.Plane087.geometry} material={materials.emissivePurpleRadialGradient} />
          <mesh geometry={nodes.Plane087_1.geometry} material={materials.palette} />
          <mesh geometry={nodes.careerText003.geometry} material={materials.careerTextOnlineTeacher} position={[0.866, 0.721, -0.952]} rotation={[1.384, 0.184, -0.768]} scale={[1.66, 1, 0.455]} />
        </group>
        <group position={[3.21, -3.232, 4.44]}>
          <mesh geometry={nodes.Plane103.geometry} material={materials.emissiveOrangeRadialGradient} />
          <mesh geometry={nodes.Plane103_1.geometry} material={materials.palette} />
          <mesh geometry={nodes.careerText004.geometry} material={materials.careerTextFreelancer} position={[0.609, 0.544, -0.736]} rotation={[1.384, 0.184, -0.768]} scale={[1.2, 1, 0.295]} />
        </group>
        <group position={[-0.793, -3.232, 2.427]}>
          <mesh geometry={nodes.Plane123.geometry} material={materials.emissivePurpleRadialGradient} />
          <mesh geometry={nodes.Plane123_1.geometry} material={materials.palette} />
          <mesh geometry={nodes.careerText005.geometry} material={materials.careerTextIRLTeacher} position={[0.75, 1.11, -0.856]} rotation={[1.384, 0.184, -0.768]} scale={[1.325, 1, 0.455]} />
        </group>
        <group position={[-2.805, -3.195, 7.432]}>
          <mesh geometry={nodes.digit0.geometry} material={materials.emissiveWhiteRadialGradient} position={[-0.625, 0.049, 0.145]} scale={0.143} />
          <mesh geometry={nodes.digit0004.geometry} material={materials.emissiveWhiteRadialGradient} position={[-0.207, 0.049, 0.145]} scale={0.143} />
          <mesh geometry={nodes.digit0005.geometry} material={materials.emissiveWhiteRadialGradient} position={[0.211, 0.049, 0.145]} scale={0.143} />
          <mesh geometry={nodes.digit0006.geometry} material={materials.emissiveWhiteRadialGradient} position={[0.629, 0.049, 0.145]} scale={0.143} />
          <mesh geometry={nodes.Plane030.geometry} material={materials.palette} />
        </group>
        <mesh geometry={nodes.Plane018.geometry} material={materials.emissiveOrangeRadialGradient} position={[1.22, -3.232, -0.582]} />
        <mesh geometry={nodes.Plane022.geometry} material={materials.emissivePurpleRadialGradient} position={[-0.793, -3.232, 2.427]} />
        <mesh geometry={nodes.Plane035.geometry} material={materials.emissiveBlueRadialGradient} position={[1.22, -3.232, 7.437]} />
        <mesh geometry={nodes.Plane048.geometry} material={materials.emissiveWhiteRadialGradient} position={[-2.792, -3.234, 7.504]} />
        <mesh geometry={nodes.Plane049.geometry} material={materials.palette} position={[-2.792, -3.232, 7.504]} />
      </group>
      <group position={[28.901, 3.273, -21.824]}>
        <group position={[-2.807, -1.74, 2.887]}>
          <mesh geometry={nodes.baguiraMesh001.geometry} material={materials.palette} position={[-0.009, 0.492, -0.079]} />
        </group>
        <group position={[-1.967, -1.74, 4.596]}>
          <mesh geometry={nodes.boyMesh.geometry} material={materials.palette} rotation={[Math.PI, -0.556, Math.PI]} />
        </group>
        <mesh geometry={nodes.hull.geometry} material={materials.darkGray} position={[-2.95, -3.273, 3.731]} />
        <group position={[-3.516, -1.74, 4.294]} scale={0.865}>
          <mesh geometry={nodes.sudoMesh003.geometry} material={materials.palette} position={[0.079, -0.507, -0.274]} scale={1.156} />
          <mesh geometry={nodes.wings.geometry} material={materials.palette} position={[0.115, -0.159, -0.216]} rotation={[1.025, 0.237, 0.114]} scale={1.156} />
        </group>
        <mesh geometry={nodes.blueskyPhysicalDynamic001.geometry} material={materials.palette} position={[4.15, -1.634, 0.476]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Cube133.geometry} material={materials.palette} position={[-2.95, -3.273, 3.731]} />
        <mesh geometry={nodes.discordPhysicalDynamic.geometry} material={materials.palette} position={[-10.764, -1.706, 3.679]} />
        <mesh geometry={nodes.gitHubPhysicalDynamic.geometry} material={materials.palette} position={[-7.852, -1.76, -2.405]} />
        <mesh geometry={nodes.linkedInPhysicalDynamic.geometry} material={materials.palette} position={[-10.053, -1.738, 0.325]} />
        <mesh geometry={nodes.mailPhysicalDynamic.geometry} material={materials.palette} position={[-1.217, -2.215, -3.357]} />
        <mesh geometry={nodes.onlyfansPhysicalDynamic.geometry} material={materials.palette} position={[10.667, -1.901, -11.383]} rotation={[0, 0.436, 0]} />
        <mesh geometry={nodes.refFan.geometry} material={materials.palette} position={[12.507, -2.624, -10.294]} />
        <mesh geometry={nodes.refStatuePhysicalDynamic.geometry} material={materials.palette} position={[-2.936, 0.035, 3.37]} />
        <mesh geometry={nodes.twitchPhysicalDynamic.geometry} material={materials.palette} position={[-4.689, -1.808, -3.991]} />
        <mesh geometry={nodes.xPhysicalDynamic.geometry} material={materials.palette} position={[4.917, -1.892, 3.711]} />
        <mesh geometry={nodes.youtubePhysicalDynamic.geometry} material={materials.palette} position={[1.97, -1.955, -2.389]} />
      </group>
      <group position={[35.76, 3.273, 13.408]}>
        <group position={[-4.122, -3.267, -1.016]}>
          <mesh geometry={nodes.Cube082.geometry} material={materials.palette} position={[0.289, 0.961, 0]} rotation={[0, 0, 0.262]} />
          <mesh geometry={nodes.refBlackboardLabelsGamepadPlaystation.geometry} material={materials.blackboardLabels} position={[0.353, 0.949, -0.006]} rotation={[Math.PI / 2, 0.262, -Math.PI / 2]} scale={0.87} />
          <mesh geometry={nodes.refBlackboardLabelsGamepadXbox.geometry} material={materials.blackboardLabels} position={[0.353, 0.949, 0]} rotation={[Math.PI / 2, 0.262, -Math.PI / 2]} scale={0.87} />
          <mesh geometry={nodes.refBlackboardLabelsMouseKeyboard001.geometry} material={materials.blackboardLabels} position={[0.347, 0.971, -0.04]} rotation={[Math.PI / 2, 0.262, -Math.PI / 2]} scale={0.87} />
        </group>
        <group position={[-2.302, -2.747, 0.182]} rotation={[0, -Math.PI / 3, 0]}>
          <mesh geometry={nodes.Cube121.geometry} material={materials.palette} position={[0.005, -0.441, -0.505]} rotation={[0, -Math.PI / 2, 0]} scale={[0.759, 0.519, 3.928]} />
          <mesh geometry={nodes.refBlower.geometry} material={materials.palette} position={[-0.01, -0.251, -0.011]} rotation={[0, -1.571, 0]} />
        </group>
        <group position={[4.036, -2.312, -4.208]} rotation={[0, 0.436, 0]}>
          <mesh geometry={nodes.Cube073.geometry} material={materials.palette} position={[0.012, -0.468, 0.01]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cylinder031.geometry} material={materials.palette} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        </group>
        <group position={[0.855, -2.74, -1.258]}>
          <mesh geometry={nodes.Cube090.geometry} material={materials.palette} position={[-1.19, 0.357, -0.178]} rotation={[0, 0.262, 0]} />
        </group>
        <group position={[3.713, -2.531, -1.973]}>
          <mesh geometry={nodes.Cube094.geometry} material={materials.palette} position={[0, -0.48, 0.004]} scale={1.294} />
          <mesh geometry={nodes.refBlade.geometry} material={materials.palette} position={[-0.158, 0.726, -0.237]} rotation={[0, Math.PI / 6, 0]} scale={1.294} />
          <mesh geometry={nodes.refHammer.geometry} material={materials.palette} position={[0.409, 1.007, -0.501]} rotation={[0, -0.611, 0]} scale={1.294} />
        </group>
        <group position={[2.088, -0.718, -5.447]} rotation={[0, Math.PI / 6, 0]}>
          <group position={[0.141, 0.013, 0.139]}>
            <mesh geometry={nodes.cube033.geometry} material={materials.palette} position={[0.152, 0.193, -0.012]} rotation={[0.016, -0.01, -0.125]} scale={0.541} />
            <mesh geometry={nodes.refel001.geometry} material={materials.projectsLabels} position={[-0.015, 0.173, 0.015]} rotation={[Math.PI / 2, 0, Math.PI / 9]} />
            <mesh geometry={nodes.text.geometry} material={nodes.text.material} position={[-0.56, -0.128, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.141, 0.758, 0.139]}>
            <mesh geometry={nodes.cube021.geometry} material={materials.palette} position={[0.008, 0.199, -0.024]} rotation={[-0.003, 0, 0.011]} scale={0.541} />
            <mesh geometry={nodes.refel002.geometry} material={materials.projectsLabels} position={[-0.103, 0.158, 0.005]} rotation={[Math.PI / 2, 0, Math.PI / 9]} />
            <mesh geometry={nodes.text001.geometry} material={nodes.text001.material} position={[-0.56, -0.133, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.141, -0.728, 0.139]}>
            <mesh geometry={nodes.cube026.geometry} material={materials.palette} position={[-0.098, 0.129, -0.016]} rotation={[-0.049, -0.008, 3.095]} scale={0.541} />
            <mesh geometry={nodes.refel.geometry} material={materials.projectsLabels} position={[-0.099, 0.164, 0.018]} rotation={[1.557, -0.108, 0.352]} />
            <mesh geometry={nodes.text002.geometry} material={nodes.text002.material} position={[-0.56, -0.133, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </group>
        </group>
        <group position={[1.211, -2.29, -3.723]} rotation={[0, 0.175, 0]}>
          <mesh geometry={nodes.awwwards.geometry} material={materials.palette} position={[-0.703, 0.003, -0.209]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.cssda.geometry} material={materials.palette} position={[0.822, 0.003, -0.161]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.fwa.geometry} material={materials.palette} position={[0.133, 0.003, 0.47]} />
        </group>
        <group position={[-0.953, 0.178, -5.064]} rotation={[0, 0.698, 0]}>
          <mesh geometry={nodes.Cube077.geometry} material={materials.palette} position={[-1.999, -1.454, 0.321]} />
          <mesh geometry={nodes.refArrowNextProject.geometry} material={materials.palette} position={[1.025, -1.358, 0.102]} />
          <mesh geometry={nodes.text003.geometry} material={nodes.text003.material} position={[1.011, -0.708, 0.118]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-1.239, -2.708, -0.441]} rotation={[0, -Math.PI / 3, 0]}>
          <mesh geometry={nodes.Cube092.geometry} material={materials.emissiveOrangeRadialGradient} position={[-0.001, 0.586, 0]} rotation={[0, -Math.PI / 2, 0]} scale={1.294} />
          <mesh geometry={nodes.Cube101.geometry} material={materials.palette} position={[-0.001, 0.586, 0]} rotation={[0, -Math.PI / 2, 0]} scale={1.294} />
          <mesh geometry={nodes.refCharcoal.geometry} material={materials.emissiveOrangeRadialGradient} position={[-0.001, 0.603, 0]} rotation={[0, -Math.PI / 2, 0]} scale={1.294} />
        </group>
        <group position={[-2.275, -2.689, -3.575]} rotation={[0, 0.698, 0]}>
          <mesh geometry={nodes.plane.geometry} material={materials.palette} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.plane001.geometry} material={materials.palette} position={[0.2, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.plane002.geometry} material={materials.palette} position={[0.4, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.plane003.geometry} material={materials.palette} position={[0.6, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.plane004.geometry} material={materials.palette} position={[0.8, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-4.018, 0.195, -2.492]} rotation={[0, 0.698, 0]}>
          <mesh geometry={nodes.cube023.geometry} material={materials.palette} position={[-1.052, -1.371, 0.03]} scale={0.712} />
          <mesh geometry={nodes.refArrowPreviousProject.geometry} material={materials.palette} position={[-1.08, -1.375, 0.102]} />
          <mesh geometry={nodes.text004.geometry} material={nodes.text004.material} position={[-1.041, -0.725, 0.118]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-2.396, 0.157, -3.678]} rotation={[0, 0.698, 0]}>
          <mesh geometry={nodes.Cube080.geometry} material={materials.palette} />
          <mesh geometry={nodes.text005.geometry} material={nodes.text005.material} position={[-0.006, -0.003, 0.022]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-2.351, -0.222, -3.622]} rotation={[0, 0.698, 0]}>
          <mesh geometry={nodes.panel.geometry} material={materials.palette} rotation={[-0.01, 0.004, 0]}>
            <mesh geometry={nodes.refIntersectUrl.geometry} material={nodes.refIntersectUrl.material} position={[0, 0, 0.035]} rotation={[1.58, 0, 0.004]} />
          </mesh>
          <mesh geometry={nodes.text006.geometry} material={nodes.text006.material} position={[-0.005, -0.002, 0.04]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <mesh geometry={nodes.carpet.geometry} material={materials.projectsCarpet} position={[1.486, -3.254, 0.782]} rotation={[0, 0.262, 0]} />
        <mesh geometry={nodes.cube024.geometry} material={materials.palette} position={[1.359, -2.446, -3.102]} rotation={[0, 0.175, 0]} scale={0.712} />
        <mesh geometry={nodes.Cube065.geometry} material={materials.palette} position={[-2.431, -3.173, -3.716]} rotation={[0, 0.698, 0]} />
        <mesh geometry={nodes.medal.geometry} material={materials.palette} position={[2.182, -2.425, -3.17]} rotation={[-0.091, 0.348, 0.016]} />
        <mesh geometry={nodes.quenchPhysicalDynamic001.geometry} material={materials.palette} position={[4.278, -2.121, -5.838]} />
        <mesh geometry={nodes.refArrowNextImage.geometry} material={materials.palette} position={[-1.664, -2.68, -4.175]} rotation={[0, 0.698, 0]} scale={0.493} />
        <mesh geometry={nodes.refArrowPreviousImage.geometry} material={materials.palette} position={[-2.969, -2.689, -3.073]} rotation={[0, 0.698, 0]} scale={0.493} />
        <mesh geometry={nodes.refel003.geometry} material={materials.projectsLabels} position={[1.315, -2.408, -3.05]} rotation={[Math.PI / 2, 0, -0.175]} />
        <mesh geometry={nodes.refImages.geometry} material={nodes.refImages.material} position={[-2.383, -1.452, -3.663]} rotation={[0, 0.698, 0]} />
        <mesh geometry={nodes.table002.geometry} material={materials.palette} position={[1.288, -2.78, -3.737]} rotation={[0, -1.396, 0]} />
      </group>
      <group position={[13.137, 3.273, 17.684]}>
        <group position={[-4.143, -3.267, -0.105]}>
          <mesh geometry={nodes.Cube100.geometry} material={materials.palette} position={[0.289, 0.961, 0]} rotation={[0, 0, 0.262]} />
          <mesh geometry={nodes.refBlackboardLabelsGamepadPlaystation001.geometry} material={materials.blackboardLabels} position={[0.345, 1.005, 0.012]} rotation={[Math.PI / 2, 0.262, -Math.PI / 2]} scale={0.87} />
          <mesh geometry={nodes.refBlackboardLabelsGamepadXbox001.geometry} material={materials.blackboardLabels} position={[0.345, 1.005, 0.01]} rotation={[Math.PI / 2, 0.262, -Math.PI / 2]} scale={0.87} />
          <mesh geometry={nodes.refBlackboardLabelsMouseKeyboard.geometry} material={materials.blackboardLabels} position={[0.352, 0.979, -0.039]} rotation={[Math.PI / 2, 0.262, -Math.PI / 2]} scale={0.87} />
        </group>
        <group position={[-2.001, -2.623, -0.382]}>
          <mesh geometry={nodes.body001.geometry} material={materials.palette} scale={0.749} />
          <mesh geometry={nodes.refHeat001.geometry} material={nodes.refHeat001.material} scale={0.749} />
          <mesh geometry={nodes.refLiquid.geometry} material={materials.emissiveOrangeRadialGradient} scale={0.749} />
        </group>
        <group position={[0.039, -2.74, -0.996]}>
          <mesh geometry={nodes.refBalls.geometry} material={materials.palette} position={[-0.848, 0.846, 0.002]} />
          <mesh geometry={nodes.refBalls001.geometry} material={materials.palette} position={[-0.848, 0.846, 0.366]} />
          <mesh geometry={nodes.refCandleFlame.geometry} material={materials.emissiveOrangeRadialGradient} position={[0.832, 0.862, 0.098]} rotation={[0, Math.PI / 4, 0]} />
          <mesh geometry={nodes.table004.geometry} material={materials.palette} position={[0.069, -0.04, -0.033]} rotation={[0, -1.309, 0]} />
        </group>
        <group position={[0.333, -0.432, -4.353]} rotation={[0, Math.PI / 6, 0]}>
          <mesh geometry={nodes.Cube166.geometry} material={materials.palette} position={[0.125, 0.489, 0.05]} />
          <mesh geometry={nodes.image.geometry} material={nodes.image.material} position={[0.125, 0.489, 0.055]} />
          <mesh geometry={nodes.intersect.geometry} material={nodes.intersect.material} position={[0.125, 0.454, 0.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.707} />
          <mesh geometry={nodes.panel001.geometry} material={materials.palette} position={[0.099, 0.111, 0.122]} />
          <mesh geometry={nodes.text008.geometry} material={nodes.text008.material} position={[0.127, 0.149, 0.123]} rotation={[Math.PI / 2, 0, 0]} scale={[0.952, 1, 1.078]} />
        </group>
        <group position={[-2.303, 0.157, -2.289]} rotation={[0, 0.698, 0]}>
          <mesh geometry={nodes.Cube178.geometry} material={materials.palette} />
          <mesh geometry={nodes.text009.geometry} material={nodes.text009.material} position={[-0.006, -0.003, 0.022]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[-2.287, -0.222, -2.262]} rotation={[0, 0.698, 0]}>
          <mesh geometry={nodes.panel002.geometry} material={materials.palette} rotation={[-0.01, 0.004, 0]}>
            <mesh geometry={nodes.refIntersectUrl001.geometry} material={nodes.refIntersectUrl001.material} position={[0, 0, 0.035]} rotation={[1.58, 0, 0.004]} />
          </mesh>
          <mesh geometry={nodes.text007.geometry} material={nodes.text007.material} position={[-0.005, -0.002, 0.04]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[2.468, -2.74, -2.221]} rotation={[0, -0.611, 0]}>
          <mesh geometry={nodes.Circle006.geometry} material={materials.palette} position={[-0.235, 0.467, 0.839]} rotation={[0, 0.611, 0]} />
          <mesh geometry={nodes.refCandleFlame002.geometry} material={materials.emissiveOrangeRadialGradient} position={[-0.016, 0.695, -0.963]} rotation={[0, 1.396, 0]} />
        </group>
        <mesh geometry={nodes.Cube003.geometry} material={materials.palette} position={[-2.362, -1.452, -2.344]} rotation={[0, 0.698, 0]} />
        <mesh geometry={nodes.refArrowNext.geometry} material={materials.palette} position={[-0.51, -0.89, -3.594]} rotation={[0, 0.698, 0]} />
        <mesh geometry={nodes.refArrowPrevious.geometry} material={materials.palette} position={[-3.939, -0.89, -0.699]} rotation={[0, 0.698, 0]} />
        <mesh geometry={nodes.refCarpet001.geometry} material={materials.labCarpet} position={[0.551, -3.254, 0.97]} rotation={[0, 0.262, 0]} />
        <mesh geometry={nodes.refChainLeft.geometry} material={materials.palette} position={[0.406, -3.273, -4.489]} rotation={[0, Math.PI / 6, 0]} />
        <mesh geometry={nodes.refChainPulley.geometry} material={materials.palette} position={[0.839, 0.772, -4.739]} rotation={[0, Math.PI / 6, 0]} />
        <mesh geometry={nodes.refChainRight.geometry} material={materials.palette} position={[1.294, -3.273, -5.002]} rotation={[0, Math.PI / 6, 0]} />
        <mesh geometry={nodes.refGearA.geometry} material={materials.palette} position={[1.015, 0.772, -4.442]} rotation={[1.578, 0.012, -0.524]} />
        <mesh geometry={nodes.refGearB.geometry} material={materials.palette} position={[0.526, 0.771, -4.152]} rotation={[1.7, 0.219, -0.538]} />
        <mesh geometry={nodes.refGearC.geometry} material={materials.palette} position={[0.139, 1.049, -3.821]} rotation={[1.578, 0.013, -0.524]} />
        <mesh geometry={nodes.refImages001.geometry} material={nodes.refImages001.material} position={[-2.313, -1.455, -2.291]} rotation={[0, 0.698, 0]} />
        <mesh geometry={nodes.refWood.geometry} material={materials.palette} position={[-2.026, -3.226, -0.118]} rotation={[2.767, 0.188, 2.753]} />
      </group>
      <group position={[12.251, 3.273, 35.251]}>
        <group position={[0.833, -2.747, -4.25]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Cube054.geometry} material={materials.palette} position={[0.005, -0.441, -0.505]} rotation={[0, -1.571, 0]} scale={[0.759, 0.519, 3.928]} />
          <mesh geometry={nodes.refBlower001.geometry} material={materials.palette} position={[-0.01, -0.251, -0.011]} rotation={[0, -1.571, 0]} />
        </group>
        <group position={[-0.962, -1.582, -3.308]}>
          <mesh geometry={nodes.Cube135.geometry} material={materials.palette} position={[-1.863, -1.344, 0.786]} rotation={[0, 0, Math.PI]} scale={[1.889, 1.299, 1.299]} />
          <mesh geometry={nodes.lava.geometry} material={materials.emissiveOrangeRadialGradient} position={[0.359, -0.469, -0.961]} rotation={[0, 1.571, 0]} scale={0.921} />
          <mesh geometry={nodes.refBanner.geometry} material={materials.cookieBanner} position={[4.76, -0.059, 0.336]} rotation={[0, 0.392, 0]} />
          <mesh geometry={nodes.refCounterPanel.geometry} material={materials.palette} position={[-0.657, 0.844, -0.526]} rotation={[-0.239, 0.252, 0.082]} />
          <mesh geometry={nodes.refOvenHeat.geometry} material={nodes.refOvenHeat.material} position={[-0.811, -0.419, -1.085]} scale={[1, 1, 0.915]} />
        </group>
        <mesh geometry={nodes.refCookie.geometry} material={materials.palette} position={[-1.819, -1.994, -1.251]} />
        <mesh geometry={nodes.tablePhysicalDynamic.geometry} material={materials.palette} position={[1.415, -2.779, 3.754]} rotation={[0, -1.571, 0]} />
      </group>
      <group position={[75.344, 0, -27.949]}>
        <group position={[0.005, 0.943, 0.008]}>
          <mesh geometry={nodes.cuboid072.geometry} material={nodes.cuboid072.material} position={[4.114, 0.317, 4.152]} rotation={[0, 0.528, 0]} scale={[2.059, 2.557, 1.546]} />
          <mesh geometry={nodes.cuboid073.geometry} material={nodes.cuboid073.material} position={[5.639, 0.317, -0.761]} rotation={[-Math.PI, 1.492, -Math.PI]} scale={[1.277, 2.107, 1.296]} />
          <mesh geometry={nodes.cuboid074.geometry} material={nodes.cuboid074.material} position={[3.835, 1.345, -4.464]} rotation={[-Math.PI, 0.703, -Math.PI]} scale={[2.123, 5.014, 2.153]} />
          <mesh geometry={nodes.cuboid075.geometry} material={nodes.cuboid075.material} position={[-1.319, 1.345, -5.785]} rotation={[Math.PI, -0.204, Math.PI]} scale={[2.201, 5.014, 2.232]} />
          <mesh geometry={nodes.cuboid076.geometry} material={nodes.cuboid076.material} position={[-5.258, 1.345, -2.722]} rotation={[Math.PI, -1.071, Math.PI]} scale={[2.201, 5.014, 2.232]} />
          <mesh geometry={nodes.cuboid077.geometry} material={nodes.cuboid077.material} position={[-2.566, 0.751, 5.218]} rotation={[0, -0.422, 0]} scale={[1.714, 3.384, 1.738]} />
          <mesh geometry={nodes.trimesh001.geometry} material={nodes.trimesh001.material} position={[-0.008, -1.124, 0.033]} />
        </group>
        <mesh geometry={nodes.Cube173.geometry} material={materials.palette} position={[-4.153, -0.141, 3.094]} rotation={[0, 0.256, 0]} scale={0.662} />
        <mesh geometry={nodes.refSkullEyes5.geometry} material={materials.emissiveOrangeRadialGradient} position={[0.157, 0.995, -4.316]} rotation={[0, 0.999, 0]} />
      </group>
      <group position={[66.875, 3.273, 66.739]}>
        <group position={[-1.341, -1.38, -3.189]} rotation={[0, 0.436, 0]}>
          <mesh geometry={nodes.refMoon.geometry} material={materials.emissiveOrangeRadialGradient} position={[-3.081, -1.944, -0.502]} />
          <mesh geometry={nodes.wood002.geometry} material={materials.palette} position={[-3.081, -1.944, -0.557]} />
        </group>
        <mesh geometry={nodes.paperPhysicalDynamic.geometry} material={materials.palette} position={[-1.867, -1.888, -1.346]} rotation={[0, -0.986, 0]} />
        <mesh geometry={nodes.paperPhysicalDynamic001.geometry} material={materials.palette} position={[-1.787, -1.895, -0.991]} rotation={[0, -0.39, 0]} />
        <mesh geometry={nodes.paperPhysicalDynamic002.geometry} material={materials.palette} position={[-1.852, -1.562, -1.175]} rotation={[0, 0.409, 0]} />
        <mesh geometry={nodes.rocks001.geometry} material={materials.palette} position={[-0.153, -3.287, -3.426]} rotation={[-2.115, 0.157, -0.209]} scale={0.477} />
        <mesh geometry={nodes.stoolPhysicalDynamic.geometry} material={materials.palette} position={[0.637, -2.614, -2.035]} rotation={[0, -0.606, 0]} />
      </group>
      <group position={[2.313, 3.273, 68.91]}>
        <group position={[4.342, -2.267, 7.087]}>
          <mesh geometry={nodes.emissive001.geometry} material={materials.emissiveOrangeRadialGradient} />
          <mesh geometry={nodes.qosdufhoqsfhosqdhf.geometry} material={materials.palette} />
        </group>
        <group position={[10.991, -3.273, -6.099]}>
          <mesh geometry={nodes.Cube177.geometry} material={materials.palette} position={[-4.092, -0.355, 0.824]} />
          <mesh geometry={nodes.Cube180.geometry} material={materials.emissivePurpleRadialGradient} position={[-4.092, -0.355, 0.824]} />
          <mesh geometry={nodes.refCrosses.geometry} material={nodes.refCrosses.material} position={[-0.947, 2.022, 0.516]} />
          <mesh geometry={nodes.refDiscs.geometry} material={nodes.refDiscs.material} position={[-0.947, 2.022, 0.516]} />
          <mesh geometry={nodes.refLabelStrike.geometry} material={materials.bowlingLabelStrike} position={[-1.878, 2.606, 0.545]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <mesh geometry={nodes.couchPhysicalDynamic.geometry} material={materials.palette} position={[-3.495, -2.161, -9.444]} />
        <mesh geometry={nodes.couchPhysicalDynamic001.geometry} material={materials.palette} position={[0.177, -2.161, -9.444]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.couchPhysicalDynamic002.geometry} material={materials.palette} position={[6.186, -2.161, -9.444]} />
        <mesh geometry={nodes.couchPhysicalDynamic003.geometry} material={materials.palette} position={[9.858, -2.161, -9.444]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Cube183.geometry} material={materials.emissivePurpleRadialGradient} position={[11.751, -3.65, 2.134]} />
        <mesh geometry={nodes.Plane042.geometry} material={materials.emissiveOrangeRadialGradient} position={[22.962, -0.709, -3.089]} rotation={[0, Math.PI / 9, 0]} />
        <mesh geometry={nodes.Plane043.geometry} material={materials.palette} position={[22.768, -0.691, -3.621]} rotation={[0, Math.PI / 9, 0]} />
        <mesh geometry={nodes.refBallPhysicalDynamic.geometry} material={materials.palette} position={[9.515, -2.3, -1.128]} />
        <group position={[11.304, -4.093, -4.561]}>
          <mesh geometry={nodes.Plane119.geometry} material={materials.emissivePurpleRadialGradient} />
          <mesh geometry={nodes.Plane119_1.geometry} material={materials.darkGray} />
        </group>
        <group position={[21.698, -1.823, -13.808]} rotation={[0, 0.175, 0]}>
          <mesh geometry={nodes.Plane143.geometry} material={materials.emissivePurpleRadialGradient} />
          <mesh geometry={nodes.Plane143_1.geometry} material={materials.emissiveOrangeRadialGradient} />
          <mesh geometry={nodes.Plane143_2.geometry} material={materials.palette} />
        </group>
        <mesh geometry={nodes.refPinPhysicalDynamic.geometry} material={materials.palette} position={[-9.194, -3.273, -0.926]} />
        <mesh geometry={nodes.sauceKetchupPhysicalDynamic.geometry} material={materials.palette} position={[-1.666, -1.671, -9.414]} />
        <mesh geometry={nodes.sauceKetchupPhysicalDynamic001.geometry} material={materials.palette} position={[7.947, -1.671, -9.694]} rotation={[Math.PI, -1.505, Math.PI]} />
        <mesh geometry={nodes.sauceKetchupPhysicalDynamic002.geometry} material={materials.palette} position={[3.857, -1.401, 7.337]} rotation={[0, 0.61, 0]} />
        <mesh geometry={nodes.sauceMustardPhysicalDynamic.geometry} material={materials.palette} position={[-1.472, -1.671, -9.758]} />
        <mesh geometry={nodes.sauceMustardPhysicalDynamic001.geometry} material={materials.palette} position={[8.277, -1.671, -9.478]} rotation={[Math.PI, -1.505, Math.PI]} />
        <mesh geometry={nodes.sauceMustardPhysicalDynamic002.geometry} material={materials.palette} position={[3.818, -1.401, 6.944]} rotation={[0, 0.61, 0]} />
        <mesh geometry={nodes.sign001.geometry} material={materials.emissiveBlueRadialGradient} position={[22.962, 2.055, -3.089]} rotation={[0, Math.PI / 9, 0]} />
        <mesh geometry={nodes.sign002.geometry} material={materials.emissiveWhiteRadialGradient} position={[22.962, 2.055, -3.089]} rotation={[0, Math.PI / 9, 0]} />
        <mesh geometry={nodes.stoolPhysicalDynamic001.geometry} material={materials.palette} position={[2.388, -2.458, 9.264]} />
        <mesh geometry={nodes.stoolPhysicalDynamic002.geometry} material={materials.palette} position={[2.503, -2.458, 4.924]} />
        <mesh geometry={nodes.stoolPhysicalDynamic003.geometry} material={materials.palette} position={[4.962, -2.458, 4.885]} />
        <mesh geometry={nodes.stoolPhysicalDynamic007.geometry} material={materials.palette} position={[4.904, -2.458, 9.187]} />
        <mesh geometry={nodes.tablePhysicalDynamic001.geometry} material={materials.palette} position={[-1.666, -2.105, -9.414]} />
        <mesh geometry={nodes.tablePhysicalDynamic002.geometry} material={materials.palette} position={[8.016, -2.105, -9.414]} />
      </group>
      <group position={[-17.744, 3.273, 7.07]}>
        <group position={[6.511, -0.284, 6.122]}>
          <mesh geometry={nodes.Cube048.geometry} material={materials.palette} position={[0, 0.075, -0.038]} />
        </group>
        <mesh geometry={nodes.blocks.geometry} material={materials.palette} position={[-59.801, -3.598, 23.993]} scale={[0.867, 0.919, 0.919]} />
        <mesh geometry={nodes.Cube088.geometry} material={materials.palette} position={[16.013, -2.274, 8.655]} />
        <mesh geometry={nodes.Cylinder022.geometry} material={materials.circuitWebgl} position={[-3.531, 0.409, -14.912]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cylinder037.geometry} material={materials.circuitWebgpu} position={[-3.531, 0.409, -14.912]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cylinder039.geometry} material={materials.circuitBrand} position={[-3.531, 0.409, -14.912]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.jump.geometry} material={materials.palette} position={[-20.452, -3.263, -43.319]} rotation={[-Math.PI / 9, 0, 0]} scale={[5, 1, 2.729]} />
        <mesh geometry={nodes.refAirDancers.geometry} material={materials.airDancer} position={[16.013, -2.274, 8.655]} />
        <mesh geometry={nodes.refAirDancers001.geometry} material={materials.airDancer} position={[-10.068, -2.274, -7.571]} rotation={[0, 0.339, 0]} />
        <mesh geometry={nodes.refBanners.geometry} material={materials.circuitBrand} position={[-1.609, -1.749, -7.035]} scale={1.152} />
        <mesh geometry={nodes.refBanners001.geometry} material={materials.circuitBrand} position={[-1.468, -1.749, 4.557]} scale={1.152} />
        <mesh geometry={nodes.refCheckpoints000.geometry} material={nodes.refCheckpoints000.material} position={[6.492, -2.411, -7.539]} scale={[10, 1.671, 1.671]} />
        <mesh geometry={nodes.refCheckpoints001.geometry} material={nodes.refCheckpoints001.material} position={[54.802, -2.411, -54.891]} rotation={[0, -1.571, 0]} scale={[10, 1.671, 1.671]} />
        <mesh geometry={nodes.refCheckpoints002.geometry} material={nodes.refCheckpoints002.material} position={[57.441, -2.411, -87.332]} rotation={[0, 1.571, 0]} scale={[10, 1.671, 1.671]} />
        <mesh geometry={nodes.refCheckpoints003.geometry} material={nodes.refCheckpoints003.material} position={[2.296, -2.411, -54.226]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10, 1.671, 1.671]} />
        <mesh geometry={nodes.refCheckpoints004.geometry} material={nodes.refCheckpoints004.material} position={[-44.064, -2.411, -34.54]} rotation={[0, 1.571, 0]} scale={[10, 1.671, 1.671]} />
        <mesh geometry={nodes.refCheckpoints005.geometry} material={nodes.refCheckpoints005.material} position={[-20.428, -2.411, -73.349]} rotation={[Math.PI, 0, Math.PI]} scale={[10, 1.671, 1.671]} />
        <mesh geometry={nodes.refCheckpoints006.geometry} material={nodes.refCheckpoints006.material} position={[-43.094, -2.411, 8.909]} rotation={[0, 1.571, 0]} scale={[10, 1.671, 1.671]} />
        <mesh geometry={nodes.refCheckpoints007.geometry} material={nodes.refCheckpoints007.material} position={[-38.301, -2.411, 63.446]} rotation={[0, -1.571, 0]} scale={[10, 1.671, 1.671]} />
        <mesh geometry={nodes.refLeaderboard.geometry} material={materials.palette} position={[-1.895, -0.152, 9.346]} />
        <mesh geometry={nodes.refLeaderboardReset.geometry} material={materials.palette} position={[-1.042, -2.762, 12.106]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic.geometry} material={materials.palette} position={[12.583, -2.297, -22.829]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic001.geometry} material={materials.palette} position={[13.311, -2.297, -30.843]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic002.geometry} material={materials.palette} position={[19.978, -2.297, -30.888]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic003.geometry} material={materials.palette} position={[18.411, -2.297, -37.777]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic004.geometry} material={materials.palette} position={[28.246, -2.297, -37.546]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic005.geometry} material={materials.palette} position={[28.284, -2.297, -40.315]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic006.geometry} material={materials.palette} position={[28.411, -2.297, -47.159]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic007.geometry} material={materials.palette} position={[23.866, -2.297, -39.235]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic008.geometry} material={materials.palette} position={[-7.315, -2.52, -2.624]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic009.geometry} material={materials.palette} position={[-2.565, -2.52, -10.912]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic010.geometry} material={materials.palette} position={[-8.79, -2.52, -1.95]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic011.geometry} material={materials.palette} position={[-7.101, -2.682, -11.161]} rotation={[0, -0.56, 0]} scale={1.165} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic012.geometry} material={materials.palette} position={[-7.412, -2.682, -8.347]} rotation={[0, 0.225, 0]} scale={1.165} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic013.geometry} material={materials.palette} position={[-5.67, -2.832, -9.331]} scale={1.165} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic014.geometry} material={materials.palette} position={[-12.727, -2.743, -3.009]} rotation={[0, -0.072, 0]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic015.geometry} material={materials.palette} position={[-12.77, -2.743, -10.907]} rotation={[-Math.PI, 1.517, -Math.PI]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic016.geometry} material={materials.palette} position={[-12.873, -2.743, -8.39]} rotation={[0, 0.094, 0]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic017.geometry} material={materials.palette} position={[-12.627, -2.743, -5.397]} rotation={[0, -0.092, 0]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic018.geometry} material={materials.palette} position={[-3.676, -2.743, 30.439]} rotation={[0, 1.048, 0]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic019.geometry} material={materials.palette} position={[-2.372, -2.743, 27.477]} rotation={[0, -0.092, 0]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic020.geometry} material={materials.palette} position={[-2.185, -2.743, 24.475]} rotation={[0, 0.128, 0]} />
        <mesh geometry={nodes.refObstaclesPhysicalKinematicPositionBased001.geometry} material={materials.palette} position={[52.187, -2.272, -87.308]} />
        <mesh geometry={nodes.refObstaclesPhysicalKinematicPositionBased002.geometry} material={materials.palette} position={[44.187, -2.272, -87.308]} />
        <mesh geometry={nodes.refObstaclesPhysicalKinematicPositionBased003.geometry} material={materials.palette} position={[36.187, -2.272, -87.308]} />
        <mesh geometry={nodes.refObstaclesPhysicalKinematicPositionBased004.geometry} material={materials.palette} position={[28.187, -2.272, -87.308]} />
        <mesh geometry={nodes.refObstaclesPhysicalKinematicPositionBased005.geometry} material={materials.palette} position={[20.187, -2.272, -84.108]} />
        <group position={[4.084, -2.263, 7.542]} rotation={[0, -Math.PI / 3, 0]}>
          <mesh geometry={nodes.Cube205.geometry} material={materials.palette} />
          <mesh geometry={nodes.Cube205_1.geometry} material={materials.circuitWebgl} />
          <mesh geometry={nodes.Cube205_2.geometry} material={materials.circuitWebgpu} />
          <mesh geometry={nodes.Cube205_3.geometry} material={materials.circuitThreejs} />
        </group>
        <mesh geometry={nodes.refRailsPhysicalFixed.geometry} material={materials.palette} position={[-9.968, -3.273, 29.609]}>
          <mesh geometry={nodes.trimesh.geometry} material={nodes.trimesh.material} position={[0, 0.01, 0]} />
        </mesh>
        <mesh geometry={nodes.refStartingLights.geometry} material={materials.emissiveGreenRadialGradient} position={[6.297, 0.631, -8.17]} />
        <mesh geometry={nodes.Text002.geometry} material={materials.emissiveOrangeRadialGradient} position={[-2.08, 3.361, 9.336]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      </group>
      <group position={[52.455, 3.273, -11.959]}>
        <group position={[1.721, -1.412, -4.102]}>
          <mesh geometry={nodes.common001.geometry} material={materials.palette} position={[0.506, -1.474, -0.229]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.emissive002.geometry} material={materials.emissiveOrangeRadialGradient} position={[0.506, -1.474, -0.229]} rotation={[0, -1.571, 0]} />
        </group>
        <group position={[-4.969, -1.412, 2.908]} rotation={[0, 1.484, 0]}>
          <mesh geometry={nodes.common002.geometry} material={materials.palette} position={[0.506, -1.474, -0.229]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.emissive003.geometry} material={materials.emissiveOrangeRadialGradient} position={[0.506, -1.474, -0.229]} rotation={[0, -1.571, 0]} />
        </group>
        <mesh geometry={nodes.refObjectsPhysicalDynamic021.geometry} material={materials.palette} position={[-3.906, -2.743, -1.932]} rotation={[0, -0.092, 0]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic022.geometry} material={materials.palette} position={[-0.886, -2.743, -4.056]} rotation={[0, -0.871, 0]} />
        <mesh geometry={nodes.refObjectsPhysicalDynamic023.geometry} material={materials.palette} position={[0.009, -2.817, 5.955]} rotation={[0.057, -0.078, 0.025]} />
      </group>
      <group position={[70.552, 3.273, 9.939]}>
        <group position={[-0.887, -3.273, 2.475]}>
          <mesh geometry={nodes.hull004.geometry} material={nodes.hull004.material} position={[0, 1, -3.999]} />
        </group>
        <mesh geometry={nodes.Cube089.geometry} material={materials.palette} position={[-0.887, -2.273, -1.524]} />
        <mesh geometry={nodes.Cube110.geometry} material={materials.emissiveBlueRadialGradient} position={[-0.887, -2.525, 2.475]} />
        <mesh geometry={nodes.refPillar.geometry} material={materials.palette} position={[-0.887, -3.273, 2.475]} />
        <mesh geometry={nodes.refWaterfallDrop.geometry} material={materials.waterfall} position={[-0.887, -2.195, -1.524]} />
        <lineSegments geometry={nodes.refWaterfallParticles.geometry} material={nodes.refWaterfallParticles.material} position={[-0.887, -2.907, -2.585]} />
        <mesh geometry={nodes.refWaterfallStill.geometry} material={materials.waterfall} position={[-0.887, -2.195, -1.524]} />
      </group>
      <group position={[-54.532, 3.273, -67.398]}>
        <group position={[0.025, -2.118, -1.748]}>
          <mesh geometry={nodes.Cube.geometry} material={materials.palette} position={[0, -0.154, -0.557]} />
          <mesh geometry={nodes.Cube005.geometry} material={materials.emissiveOrangeRadialGradient} position={[0, -0.154, -0.557]} />
          <mesh geometry={nodes.refScreen.geometry} material={materials.palette} position={[0, -0.154, -0.672]} />
        </group>
        <mesh geometry={nodes.Cube006.geometry} material={materials.palette} position={[0.025, -3.126, -0.191]} scale={1.182} />
        <mesh geometry={nodes.Cube007.geometry} material={materials.emissiveGreenRadialGradient} position={[-0.52, -2.997, 0.323]} />
        <mesh geometry={nodes.Cube008.geometry} material={materials.palette} position={[-1.91, -3.142, -1.354]} rotation={[0.043, 0.494, -0.013]} scale={0.821} />
        <mesh geometry={nodes.Cube009.geometry} material={materials.palette} position={[-1.886, -2.924, -1.36]} rotation={[0.054, 0.979, -0.02]} scale={0.821} />
        <mesh geometry={nodes.cupPhysicalDynamic.geometry} material={materials.palette} position={[0.509, -1.04, -1.751]} />
        <mesh geometry={nodes.cupPhysicalDynamic001.geometry} material={materials.palette} position={[0.061, -1.04, -1.987]} />
        <mesh geometry={nodes.cupPhysicalDynamic002.geometry} material={materials.palette} position={[1.266, -3.127, -1.686]} rotation={[-0.123, -0.058, -0.115]} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials.palette} position={[0.898, -3.08, -0.077]} rotation={[-0.19, -0.295, -0.55]} scale={0.857} />
        <mesh geometry={nodes.Plane005.geometry} material={materials.palette} position={[-0.184, -3.214, 0.504]} />
        <mesh geometry={nodes.stoolPhysicalDynamic004.geometry} material={materials.palette} position={[0.013, -2.237, 1.863]} rotation={[-0.142, 0.749, 0.072]} />
      </group>
    </group>
  )
}

useGLTF.preload('/areas.glb')
