/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/uav/uav.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/uav.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.151}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.pCone3_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pCone4_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pCone5_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pCube1_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pCube3_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pCylinder1_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.pSphere1_lambert2_0.geometry} material={materials.lambert2} />
        </group>
      </group>
      <mesh geometry={nodes.Apartment1_BaseMaterial_0.geometry} material={materials.BaseMaterial} position={[-1783.508, 129.617, -2330.855]} rotation={[-Math.PI / 2, 0, 0]} scale={-16.004} />
    </group>
  )
}

useGLTF.preload('/uav.glb')
